use super::gpu_profile::GpuProfile;

pub static GPU_PROFILES_WINDOWS: &[GpuProfile] = &[
    // NVIDIA RTX 3060
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    // NVIDIA RTX 4090
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4090, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d12",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 24,
    },
    // NVIDIA GTX 1650
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1650, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    // Intel Iris Xe
    GpuProfile {
        webgl_vendor: "Google Inc. (Intel)",
        webgl_renderer: "ANGLE (Intel, Intel(R) Iris(R) Xe Graphics, D3D11)",
        webgpu_vendor: "intel",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    // Intel UHD Graphics 630
    GpuProfile {
        webgl_vendor: "Google Inc. (Intel)",
        webgl_renderer: "ANGLE (Intel, Intel(R) UHD Graphics 630, D3D11)",
        webgpu_vendor: "intel",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 6,
    },
    // AMD Radeon RX 6700 XT
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX 6700 XT, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    // AMD Radeon RX 5600 XT
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX 5600 XT, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    // AMD Radeon RX Vega 10 Graphics (integrated GPU, common on Ryzen laptops)
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX Vega 10 Graphics, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    // NVIDIA RTX 2060
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 2060, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    // Intel Arc A750 Graphics
    GpuProfile {
        webgl_vendor: "Google Inc. (Intel)",
        webgl_renderer: "ANGLE (Intel, Intel(R) Arc(TM) A750 Graphics, D3D12)",
        webgpu_vendor: "intel",
        webgpu_architecture: "d3d12",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 16,
    },
    // ── NVIDIA RTX 40-series ──
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4060, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Ti, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 Ti, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d12",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 16,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4080, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d12",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 16,
    },
    // ── NVIDIA RTX 30-series ──
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3050, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3070, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Ti, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3080, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 16,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Ti, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 16,
    },
    // ── NVIDIA GTX 16/10-series (hugely popular) ──
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1080, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    // ── NVIDIA Laptop GPUs ──
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Laptop GPU, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 Laptop GPU, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d12",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (NVIDIA Corporation)",
        webgl_renderer: "ANGLE (NVIDIA, NVIDIA GeForce MX550, D3D11)",
        webgpu_vendor: "nvidia",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 4,
    },
    // ── AMD Radeon discrete ──
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX 6600, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX 6600 XT, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX 6800 XT, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 16,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX 7600, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX 7800 XT, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d12",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 16,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX 7900 XTX, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d12",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 24,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon RX 580, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    // ── AMD Integrated (very common on Ryzen laptops) ──
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon Graphics, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon(TM) 780M Graphics, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 16,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (AMD)",
        webgl_renderer: "ANGLE (AMD, AMD Radeon(TM) 680M, D3D11)",
        webgpu_vendor: "amd",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    // ── Intel Integrated (extremely common on laptops) ──
    GpuProfile {
        webgl_vendor: "Google Inc. (Intel)",
        webgl_renderer: "ANGLE (Intel, Intel(R) UHD Graphics 620, D3D11)",
        webgpu_vendor: "intel",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 4,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (Intel)",
        webgl_renderer: "ANGLE (Intel, Intel(R) UHD Graphics 730, D3D11)",
        webgpu_vendor: "intel",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (Intel)",
        webgl_renderer: "ANGLE (Intel, Intel(R) UHD Graphics 770, D3D11)",
        webgpu_vendor: "intel",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 8,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (Intel)",
        webgl_renderer: "ANGLE (Intel, Intel(R) Iris(R) Plus Graphics, D3D11)",
        webgpu_vendor: "intel",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 4,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (Intel)",
        webgl_renderer: "ANGLE (Intel, Intel(R) HD Graphics 530, D3D11)",
        webgpu_vendor: "intel",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 4,
    },
    GpuProfile {
        webgl_vendor: "Google Inc. (Intel)",
        webgl_renderer: "ANGLE (Intel, Intel(R) HD Graphics 630, D3D11)",
        webgpu_vendor: "intel",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 4,
    },
    // ── Qualcomm Adreno (Snapdragon X laptops) ──
    GpuProfile {
        webgl_vendor: "Google Inc. (Qualcomm)",
        webgl_renderer: "ANGLE (Qualcomm, Qualcomm(R) Adreno(TM) X1-85, D3D11)",
        webgpu_vendor: "qualcomm",
        webgpu_architecture: "d3d11",
        canvas_format: "rgba8unorm",
        hardware_concurrency: 12,
    },
];
